/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeekRouteImport } from './routes/week'
import { Route as ListRouteImport } from './routes/list'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MealsIndexRouteImport } from './routes/meals/index'
import { Route as IngredientsIndexRouteImport } from './routes/ingredients/index'
import { Route as MealsMealIdRouteImport } from './routes/meals/$mealId'
import { Route as IngredientsIngredientIdRouteImport } from './routes/ingredients/$ingredientId'
import { Route as MealsMealIdEditRouteImport } from './routes/meals_.$mealId.edit'
import { Route as IngredientsIngredientIdEditRouteImport } from './routes/ingredients_.$ingredientId.edit'

const WeekRoute = WeekRouteImport.update({
  id: '/week',
  path: '/week',
  getParentRoute: () => rootRouteImport,
} as any)
const ListRoute = ListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsIndexRoute = MealsIndexRouteImport.update({
  id: '/meals/',
  path: '/meals/',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsIndexRoute = IngredientsIndexRouteImport.update({
  id: '/ingredients/',
  path: '/ingredients/',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsMealIdRoute = MealsMealIdRouteImport.update({
  id: '/meals/$mealId',
  path: '/meals/$mealId',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsIngredientIdRoute = IngredientsIngredientIdRouteImport.update({
  id: '/ingredients/$ingredientId',
  path: '/ingredients/$ingredientId',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsMealIdEditRoute = MealsMealIdEditRouteImport.update({
  id: '/meals_/$mealId/edit',
  path: '/meals/$mealId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsIngredientIdEditRoute =
  IngredientsIngredientIdEditRouteImport.update({
    id: '/ingredients_/$ingredientId/edit',
    path: '/ingredients/$ingredientId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/list': typeof ListRoute
  '/week': typeof WeekRoute
  '/ingredients/$ingredientId': typeof IngredientsIngredientIdRoute
  '/meals/$mealId': typeof MealsMealIdRoute
  '/ingredients': typeof IngredientsIndexRoute
  '/meals': typeof MealsIndexRoute
  '/ingredients/$ingredientId/edit': typeof IngredientsIngredientIdEditRoute
  '/meals/$mealId/edit': typeof MealsMealIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/list': typeof ListRoute
  '/week': typeof WeekRoute
  '/ingredients/$ingredientId': typeof IngredientsIngredientIdRoute
  '/meals/$mealId': typeof MealsMealIdRoute
  '/ingredients': typeof IngredientsIndexRoute
  '/meals': typeof MealsIndexRoute
  '/ingredients/$ingredientId/edit': typeof IngredientsIngredientIdEditRoute
  '/meals/$mealId/edit': typeof MealsMealIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/list': typeof ListRoute
  '/week': typeof WeekRoute
  '/ingredients/$ingredientId': typeof IngredientsIngredientIdRoute
  '/meals/$mealId': typeof MealsMealIdRoute
  '/ingredients/': typeof IngredientsIndexRoute
  '/meals/': typeof MealsIndexRoute
  '/ingredients_/$ingredientId/edit': typeof IngredientsIngredientIdEditRoute
  '/meals_/$mealId/edit': typeof MealsMealIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/list'
    | '/week'
    | '/ingredients/$ingredientId'
    | '/meals/$mealId'
    | '/ingredients'
    | '/meals'
    | '/ingredients/$ingredientId/edit'
    | '/meals/$mealId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/list'
    | '/week'
    | '/ingredients/$ingredientId'
    | '/meals/$mealId'
    | '/ingredients'
    | '/meals'
    | '/ingredients/$ingredientId/edit'
    | '/meals/$mealId/edit'
  id:
    | '__root__'
    | '/'
    | '/list'
    | '/week'
    | '/ingredients/$ingredientId'
    | '/meals/$mealId'
    | '/ingredients/'
    | '/meals/'
    | '/ingredients_/$ingredientId/edit'
    | '/meals_/$mealId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ListRoute: typeof ListRoute
  WeekRoute: typeof WeekRoute
  IngredientsIngredientIdRoute: typeof IngredientsIngredientIdRoute
  MealsMealIdRoute: typeof MealsMealIdRoute
  IngredientsIndexRoute: typeof IngredientsIndexRoute
  MealsIndexRoute: typeof MealsIndexRoute
  IngredientsIngredientIdEditRoute: typeof IngredientsIngredientIdEditRoute
  MealsMealIdEditRoute: typeof MealsMealIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/week': {
      id: '/week'
      path: '/week'
      fullPath: '/week'
      preLoaderRoute: typeof WeekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list': {
      id: '/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof ListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals/': {
      id: '/meals/'
      path: '/meals'
      fullPath: '/meals'
      preLoaderRoute: typeof MealsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/': {
      id: '/ingredients/'
      path: '/ingredients'
      fullPath: '/ingredients'
      preLoaderRoute: typeof IngredientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals/$mealId': {
      id: '/meals/$mealId'
      path: '/meals/$mealId'
      fullPath: '/meals/$mealId'
      preLoaderRoute: typeof MealsMealIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/$ingredientId': {
      id: '/ingredients/$ingredientId'
      path: '/ingredients/$ingredientId'
      fullPath: '/ingredients/$ingredientId'
      preLoaderRoute: typeof IngredientsIngredientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals_/$mealId/edit': {
      id: '/meals_/$mealId/edit'
      path: '/meals/$mealId/edit'
      fullPath: '/meals/$mealId/edit'
      preLoaderRoute: typeof MealsMealIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients_/$ingredientId/edit': {
      id: '/ingredients_/$ingredientId/edit'
      path: '/ingredients/$ingredientId/edit'
      fullPath: '/ingredients/$ingredientId/edit'
      preLoaderRoute: typeof IngredientsIngredientIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ListRoute: ListRoute,
  WeekRoute: WeekRoute,
  IngredientsIngredientIdRoute: IngredientsIngredientIdRoute,
  MealsMealIdRoute: MealsMealIdRoute,
  IngredientsIndexRoute: IngredientsIndexRoute,
  MealsIndexRoute: MealsIndexRoute,
  IngredientsIngredientIdEditRoute: IngredientsIngredientIdEditRoute,
  MealsMealIdEditRoute: MealsMealIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
